fix: add `eager` as options to types and docs
ember-modifier/ember-modifier pull request #855
Opened 2024-06-28 05:22 UTC by aklkv

2024-06-29 11:51 UTC, NullVoxPopuli requested changes
The option is not in the current version of ember-modifier -- it was in the previous major.

Only folks using v3 need to add eager false

2024-06-29 11:51 UTC, NullVoxPopuli commented on README.md
> -- [Compatibility](#compatibility)
Why'd this change?

2024-06-29 11:53 UTC, NullVoxPopuli commented
If you wanted to update the v3 readme, that'd be fine 🎉

2024-07-03 18:55 UTC, SergeAstapov commented
Agree with @NullVoxPopuli, this option does not exist in v4 hence IMO this is not a legit change

2024-07-03 18:57 UTC, aklkv commented
@SergeAstapov yeah we synced up with @NullVoxPopuli on Discord and in alignment. I think I will close this PR and when time permits add notes to v3 docs

2024-07-03 18:57 UTC, closed without merging